### ISSUE TITLE
how to ...

### ISSUE THREAD

**Issue by ghost** [KiraYamato94/LasMonjas#1]
i am a chinese , but i can speak English . i want to chinese the mod. **how to chinese the mod** Can you teach me ?

**Comment by KiraYamato94** [comment]
There's an already group of people who made the translation to Chinese of the mod, I just don't remember the webpage where the mod is

**Comment by ghost** [comment]
e

**Comment by ghost** [comment]
I've sinicized this mod and I just don't know where to put this file

**Comment by ghost** [comment]
[RoleInfo.zip](https://github.com/KiraYamato94/LasMonjas/files/9078494/RoleInfo.zip)

**Comment by ghost** [comment]
i can find some mod , Such as https://github.com/mingyoushe/Amongus-MOD-China .but it is chinese，I don't think you can read it. Maybe I was being rude

**Comment by ghost** [comment]
You should be the creator of this mod. I want to Chinese this mod
Do you know where the identity files you set up when designing this mod are? Tell me. Thank you. 
this is what amongus looks when Las Monjas is&nbsp;added.
Where is the file that you set your identity to place?&nbsp;
