### ISSUE TITLE
 Application Letter for Translation Authorization 

### ISSUE THREAD

**Issue by ZeMingoh233** [KiraYamato94/LasMonjas#11]
Dear KiraYamato94,

We are a group of amateur Chinese translators of modules for the game among us. We are an nonprofit organization trying to introduce popular modules to Chinese mainland game players, and is responsible for translating the module of Las Monjas.  

According to China's Copyright Laws, we have to obtain the authorization of copyright owner to make our translation to the public, or played and developed based on our translation. What's more, we need to timely correct mistakes and untranslated portions after we issue the translated files. We hereby apply for your authorization for the Chinese Simplified Characters translation. Neither will we charge any fees for our translation work from you nor reap profit from our work. If we have the honor to obtain your authorization, we will continue to sinicize the modules you release at the first time and provide them to local players.  

 Four Han sinicization groups ZeMing(OH)233

**Comment by KiraYamato94** [comment]
Good morning! I really appreciate that, you have my authorization as long as you keep "Las Monjas *mod version*" text under the ping message (located in CredentialsPatch.cs), that's my only petition please :)

Regards, Allul.

**Comment by ZeMingoh233** [comment]
Thank you very much!
