### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by ghost** [KiraYamato94/LasMonjas#11]
Hello, the original author of LasMonjas.
I asked you before how to Chineseize Mod,
I have repeatedly sinicized and found that it all comes from the file "LasMonjas.cs"
I suspect a "using (a library)" is missing do you know how to fix the problem

**Comment by KiraYamato94** [comment]
All the needed files to compile the mod are included on the source code on github, I don't know what are you talking about

**Comment by ghost** [comment]
Simply put: I don't think you have a compilation problem, but I do. Suggestions for compile-time errors show whether you are missing code or not calling libraries. This can result in a large number of problems in the same file
