### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by TianMengLucky** [KiraYamato94/LasMonjas#14]
I don't know, have you considered support for other languages?

**Comment by Bidge-CTG** [comment]
We are a group of Sinicized group, as he said, we want to Sinicize your Mod. Please let us translate your Mod, thank you

**Comment by KiraYamato94** [comment]
Good morning, you can translate the mod. I can't add more languages if I don't know how to speak/write those languages to be honest. I only need you to keep the "Las Monjas *modversion*" message under the ping message and the one "made by Allul" on the main menu :)

![imagen](https://user-images.githubusercontent.com/1362150/182084483-d7b74486-ece3-400e-be32-c147e2926b16.png)
![imagen](https://user-images.githubusercontent.com/1362150/182084551-47c18215-ccdc-47ef-9a1b-25ada3454fa6.png)

**Comment by Bidge-CTG** [comment]
Thank You，We Will.
