### ISSUE TITLE
I can't sinicize it. I'm sorry

### ISSUE THREAD

**Issue by Bidge-CTG** [KiraYamato94/LasMonjas#15]
Hello, original LasMonjas author.
I researched for a long time。
but couldn't find the third-party libraries needed for Lasmonjas.
So I can't sinicize it. I'm sorry。

There are some Chinese versions of others in China.
But it's full of ads promoting their Sinicized group.

**Comment by Bidge-CTG** [comment]
Sorry

**Comment by Bidge-CTG** [comment]
Maybe I'll work on it for a while. Thanks for your mod

**Comment by Bidge-CTG** [comment]
![image](https://user-images.githubusercontent.com/110298593/184471121-44db3bc6-1bae-42b0-868b-cc35b911a7ab.png)
![image](https://user-images.githubusercontent.com/110298593/184471147-6c318f83-76db-4a5a-b0a3-35ee080a6f50.png)

**Comment by KiraYamato94** [comment]
Good morning, it's been a while. If you still want to translate the mod, I can send you a file with the text I need to be translated and then I'll make a build for Chinese translation.

**Comment by KiraYamato94** [comment]
Good morning, it's been a while. If you still want to translate the mod, open a new issue and I'l send you a file with the text I need to be translated and then I'll make a build for Chinese translation.
