### ISSUE TITLE
I have received your reply.

### ISSUE THREAD

**Issue by Bidge-CTG** [KiraYamato94/LasMonjas#16]
I have received your reply. You can send me the documents to be translated in a form

**Comment by KiraYamato94** [comment]
Hello again, can you tell me an email to send the file? It's a .ods file (Libre Office Calc file)

**Comment by Bidge-CTG** [comment]
3448851731@qq.com

**Comment by KiraYamato94** [comment]
Done confirm me if you recieved it and can open the file. Also the file contais spoilers for the next update, so please keep them as a secret until the update is released.
