### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by TianMengLucky** [KiraYamato94/LasMonjas#17]
Is it possible to switch languages automatically by using code similar to the one in the picture below instead of using instructions?
![Snipaste_2022-11-16_23-21-19](https://user-images.githubusercontent.com/107238739/202221372-26f54b89-1fef-41d1-a085-935b80e23210.png)

**Comment by KiraYamato94** [comment]
Hello, I have that idea in mind for the future, but right know I need to be able to switch languages whenever I want to check translation issues (and also understand the base game itself while testing since I don't know many of the supported languages)

**Comment by TianMengLucky** [comment]
> Hello, I have that idea in mind for the future, but right know I need to be able to switch languages whenever I want to check translation issues (and also understand the base game itself while testing since I don't know many of the supported languages)

Oh, I see. I think we can add automatic language selection without switching commands

**Comment by MC-AS-Huier** [comment]
> Hello, I have that idea in mind for the future, but right know I need to be able to switch languages whenever I want to check translation issues (and also understand the base game itself while testing since I don't know many of the supported languages)

Speaking of translation, I found that the four preset options in the game showed four modes of the game
