### ISSUE TITLE
Respawn is broken

### ISSUE THREAD

**Issue by RadicalRhino353** [KiraYamato94/LasMonjas#19]
on gamemodes like capture the flag and king of the hill, most people cant respawn (i was the only one who could)

**Comment by KiraYamato94** [comment]
Good morning! Just tested it and worked fine, probably a mod reinstallation will solve the issue, you can join our discord and open a ticket there to get support faster :) . Also if you can provide the following information please:

- Mod version used
- Region used
- Where you the game host?
