### ISSUE TITLE
host venting / low ping (1 issue, 1 suggestion)

### ISSUE THREAD

**Issue by acar1122** [KiraYamato94/LasMonjas#2]
issue : in capture the flag, the host can get stuck in the vents when trying to vent. this is fixed by the enemy kills them. this is only a problem for the host. 

suggestion for a different issue : people with bad ping almost always die before they kill in capture the flag and cops vs thieves when they should have been able to trade kills. with this, they sorta dont like playing for long because its frustrating always losing a spam kill button battle when it should be a draw. lets say we have the kill cooldown at 10 seconds. i am suggestion that you can click the kill button at any time (even when your not in kill range) but if you miss, you have 1 second or half a second kill cooldown, but of corse if you kill you still have the 10 second cooldown. this shouldnt be a main feature, but i think it should be a setting so its more injoyable for those with high ping. if you are able to add this, please do.. we find your mod very enjoyable and i hate for them to miss out because of something like this

**Comment by KiraYamato94** [comment]
Hmm yeah I suffered the host venting problem in Dleks not so much ago, don't know what's causing it right now unfortunately.

About the 1 second cooldown option, I'll take a note for it
