### ISSUE TITLE
One problem remains unsolved

### ISSUE THREAD

**Issue by ghost** [KiraYamato94/LasMonjas#2]
One problem remains unsolved
You should be the creator of this mod. I want to Chinese this mod
Do you know where the identity files you set up when designing this mod are? Tell me. Thank you. 
![image](https://user-images.githubusercontent.com/106727385/178136598-5ef349fb-184d-45fe-9edc-64d5a39a0f44.png)
this is what amongus looks when Las Monjas is added.
Where is the file that you set your identity to place?
![YYLE1KWP{H)DK3RIJL$U`BU](https://user-images.githubusercontent.com/106727385/178137131-0f4eae9e-73e9-482a-b94d-13230ed43d36.png)

**Comment by KiraYamato94** [comment]
To translate the mod you need to download the mod source, edit its source code and build it again. If you can't do that I can't help

**Comment by ghost** [comment]
thanks

**Comment by ghost** [comment]
What is the "Jinx" identity in the mod
