### ISSUE TITLE
updates being an issue

### ISSUE THREAD

**Issue by acar1122** [KiraYamato94/LasMonjas#3]
theres a big issue where we have half of our lobby able to download it properly, but a select few had issues of them always being on an older version of the game. they uninstalled and reinstalled among us, checked for updates, used ur most recent mod version... we spend a whole hour trying to troubleshoot and it kept saying "you are running an older version of the game". eventually they just gave up. is it possible if you can add the normal among us version that you intend us to use inside the zip file that we have to download? this might fix the issue

**Comment by acar1122** [comment]
ones using v2022.2.23s and the other is using v2022.2.8s and it wont change

**Comment by KiraYamato94** [comment]
Hello there! I've intend to update the mod to the latest among us Steam version, it's true that 2022.2.23 came out yesterday out of nowhere and it's giving me some problems. About the part of including the normal among us version with the mod, I can't do that, it's against the oficial Among Us Mod Policy https://www.innersloth.com/among-us-mod-policy/
