### ISSUE TITLE
buid code

### ISSUE THREAD

**Issue by ghost** [KiraYamato94/LasMonjas#3]
I have made this code Chinese
Do you know how the source code is compiled into a DLL that can be imported into Amongus
And potentially copyrighted mods with bugs that need to be addressed
You can send me an email
My email address   3448851731@qq.com

**Comment by KiraYamato94** [comment]
You need to install a program that can compile code with a working enviroment, do you have any experience with it?

**Comment by ghost** [comment]
i do. **I can use Microsoft Visit Studio** .but I don’t know 
But I don't know what language to compile it in. Such as C + +, C, python
**But I haven't used C#.** I often edit code in python and have some experience with C++
Can you show me how to compile this code

**Comment by ghost** [comment]
i can try some other program ,and install it.

**Comment by ghost** [comment]
Now in Beijing is  10:00 in the morning. Maybe in Spain is too late.

**Comment by KiraYamato94** [comment]
Check this tutorial to learn how to build for among us https://docs.reactor.gg/

**Comment by ghost** [comment]
I watched [passage](https://docs.reactor.gg) on the article 
But I thought about it and couldn't see where the source code was needed
The source code is the article you published [Las Monjas](https://github.com/KiraYamato94/LasMonjas/)
the tip of https://docs.reactor.gg/quick_start/install_configure_ide/ 
Tip:
└── ModExperiment
    ├── ModExperiment
    │   ├── ModExperiment.csproj
    │   └── TemplatePlugin.cs
    └── ModExperiment.sln
In this tip, Is this file(ModExperiment.croproj)equal to las monjas.csproj?

**Comment by KiraYamato94** [comment]
The file(ModExperiment.croproj) isn't equal to las monjas.csproj, that tutorial is just to set up the enviroment so you can build lasmonjas

**Comment by ghost** [comment]
If I've set up the environment,
So how do I compile Las Monjas source code?
Do I need to run the command（dotnet build）?

**Comment by KiraYamato94** [comment]
Yes

**Comment by ghost** [comment]
I found a lot of errors after compiling this program, I don't know how these errors are generated, I went to Github to download LasMonjas source code again, but the problem could not be solved
![image](https://user-images.githubusercontent.com/106727385/179146812-269df7d9-ef09-49b3-9883-fccc764d338c.png)
This is Chinese, it mean  You have 1 warning, 1971 errors

**Comment by ghost** [comment]
I downloaded different versions of [Dotnet](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) in a row and couldn't solve it

**Comment by ghost** [comment]
Examples are 6.0.0 and 6.0.7

**Comment by ghost** [comment]
do you konw why?

**Comment by ghost** [comment]
If you have time, you can send me your Dotnet installer, thanks
