### ISSUE TITLE
i cant build this mod，how to build？

### ISSUE THREAD

**Issue by ghost** [KiraYamato94/LasMonjas#5]
I wanted to Chinese this mod, but I had a problem with the end part of the process I can not compile this mod, you can use video, screenshots to give me a detailed explanation of the Chinese use Dotnet version, and the compilation process

**Comment by KiraYamato94** [comment]
If you can't build the mod just after download the source code and following the documention on reactor.gg that I gave you, I can't help you anymore, sorry
