### ISSUE TITLE
joining a server creates error

### ISSUE THREAD

**Issue by acar1122** [KiraYamato94/LasMonjas#6]
61: client sent unregistered call
i can create a lobby, but the moment someone tries to join, this error happens

quite a few of the group are starting to give up on the mod because off the errors. i know its not ur fault... but they are getting sick of the problems that keep happening recently

**Comment by KiraYamato94** [comment]
Hello there! Unfortunately for me, I released the mod just when among us authors decided to made a lot of Steam updates that messed up the mod. I'm trying to do my best to fix Steam's issues but 2022.2.23s it's giving custom server errors sometimes, I'm not having any issues with my own impostor test server but yeah I know how the feel. Sorry to hear that but at the moment I can't do more :(. Thx for trying at least :)
