### ISSUE TITLE
Could you please add option allowing ghosts to see the other players' roles?

### ISSUE THREAD

**Issue by ZeMingoh233** [KiraYamato94/LasMonjas#9]
Hello there, I'm one of Among us mod fans from China, and we have played Las Monjas for some time. We love your mod so much and we even manage to translate it into Chinese. However, we find some inconvenience during our playing, and the worst is that we can't see everyone's roles when we died and became ghosts. I know that because of roles like Spiritualist, it will be unbalanced if dead players can immediately see the roles of others, but how about let ghosts see the roles not immediately but after the task period, so that there's no way for them to revive? We'll appreciate a lot if you can apply this into your mod!
By the way, we can send you a copy of our translation if you'd like to;)

**Comment by KiraYamato94** [comment]
Good morning! Thanks for the feedback, I'm trying to add the option for ghost can see roles only if their body has been reported. This way i think it would be balanced, didn't manage to code it yet but its on my plans for future updates :). Also thanks for translating it to Chinese, there's no need to send me a copy, as a petition just don't remove the "Las Monjas -mod version-" message displayed under the ping message in game please :)
